version: 1.0.{build}

platform: x64

branches:
  only:
    - master

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;C:\go\bin;%PATH%
  - go version
  - go env 

build_script:
  - go build -o bifextract.exe -i .
  - go test -v

artifacts:
  - path: bifextract.exe
  - name: binary